/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.dao.MuonSachCT01DAO;
import com.ebooks.dao.NhaXuatBanDAO;
import com.ebooks.dao.TacGiaDAO;
import com.ebooks.dao.TheLoaiDAO;
import com.ebooks.helper.DialogHelper;
import com.ebooks.helper.MovingForm;
import com.ebooks.helper.ShareHelper;
import com.ebooks.model.MuonSachCT01;
import com.ebooks.model.NhaXuatBan;
import com.ebooks.model.TacGia;
import com.ebooks.model.TaiKhoan;
import com.ebooks.model.TheLoai;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinh
 */
public class ManagerBorrowDiaLog extends javax.swing.JDialog {

    boolean congTac = false;

    public ManagerBorrowDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        MovingForm.initMoving(this, pnlMain);
        fillCboTheloai();
        fillCboTacGia();
    }

    private void fillCboTheloai() {
        TheLoaiDAO DAOTL = new TheLoaiDAO();
        List<TheLoai> ListTL = new ArrayList<TheLoai>();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTheLoai.getModel();
        model.removeAllElements();
        ListTL = DAOTL.selectAll();
        model.addElement("TB000: Tất cả");
        for (TheLoai theLoai : ListTL) {
             model.addElement(theLoai.getMaTheLoai()+": " + theLoai.getTenTheLoai());
        }
    }
    
    private void fillCboTacGia() {
        TacGiaDAO DAOTG = new TacGiaDAO();
        List<TacGia> ListTG = new ArrayList<TacGia>();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTacGia.getModel();
        model.removeAllElements();
        ListTG = DAOTG.selectAll();
        model.addElement("TG000: Tất cả");
        for (TacGia tacGia : ListTG) {
             model.addElement(tacGia.getMaTacGia()+": " + tacGia.getHoTen());
        }
    }
    
    
    
     private void fillTableMuonSachTB_AB() {
        List<MuonSachCT01> ListMS01 = new ArrayList<>();
         MuonSachCT01DAO DAOMS01 = new MuonSachCT01DAO();
        DefaultTableModel model;
        model = (DefaultTableModel) tblTheLoai_TacGia.getModel();
        tblTheLoai_TacGia.setSelectionBackground(new Color(87, 190, 110));
        model.setRowCount(0);
        try {
            ListTK = DAOTK.selectByKeyword(txtTimTaiKhoan.getText());
            for (TaiKhoan taiKhoan : ListTK) {
                Object[] row = {};
                model.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        tabTacGia = new javax.swing.JTabbedPane();
        panelRound2 = new com.ebooks.Compoment.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTheLoai_TacGia = new com.ebooks.Compoment.Table();
        btnLast = new com.ebooks.Compoment.MyButton();
        btnNext = new com.ebooks.Compoment.MyButton();
        btnPrev = new com.ebooks.Compoment.MyButton();
        btnFirst = new com.ebooks.Compoment.MyButton();
        cboTheLoai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cboTacGia = new javax.swing.JComboBox<>();
        panelRound3 = new com.ebooks.Compoment.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFirst1 = new com.ebooks.Compoment.MyButton();
        btnPrev1 = new com.ebooks.Compoment.MyButton();
        btnNext1 = new com.ebooks.Compoment.MyButton();
        btnLast1 = new com.ebooks.Compoment.MyButton();
        panelRound4 = new com.ebooks.Compoment.PanelRound();
        txtTimTacGia = new com.ebooks.Compoment.SearchText();
        btnTimTacGia = new com.ebooks.Compoment.MyButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTacGia1 = new com.ebooks.Compoment.Table();
        panelRound5 = new com.ebooks.Compoment.PanelRound();
        txtTenDangNhap = new javax.swing.JTextField();
        lblTenDangNhap = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        lblMaSach = new javax.swing.JLabel();
        txtNgayMuon = new javax.swing.JTextField();
        lblNgayMuon = new javax.swing.JLabel();
        Calendar = new com.toedter.calendar.JCalendar();
        btnIconCld1 = new com.ebooks.Compoment.MyButton();
        txtTenSach = new javax.swing.JTextField();
        lblTenSach = new javax.swing.JLabel();
        txtMaMuonSach = new javax.swing.JTextField();
        lblMaMuonSach = new javax.swing.JLabel();
        txtMaMuonSachChiTiet = new javax.swing.JTextField();
        lblMaMuonSachChiTiet = new javax.swing.JLabel();
        btnCapNhat = new com.ebooks.Compoment.MyButton();
        btnResetForm = new com.ebooks.Compoment.MyButton();
        btnHuyMuon = new com.ebooks.Compoment.MyButton();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlMain.setBackground(new java.awt.Color(254, 254, 254));
        pnlMain.setRoundBottomLeft(20);
        pnlMain.setRoundBottomRight(20);
        pnlMain.setRoundTopLeft(20);
        pnlMain.setRoundTopRight(20);
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlMain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tabTacGia.setBackground(new java.awt.Color(255, 255, 255));
        tabTacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabTacGia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabTacGiaStateChanged(evt);
            }
        });

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTheLoai_TacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã mượn chi tiết", "Tên sách", "Tên đăng nhập", "Thời gian mượn", "Thể loại", "Tác giả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTheLoai_TacGia.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTheLoai_TacGia.getTableHeader().setReorderingAllowed(false);
        tblTheLoai_TacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTheLoai_TacGiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTheLoai_TacGia);

        panelRound2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 850, 290));

        btnLast.setBackground(new java.awt.Color(145, 227, 168));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-right.png"))); // NOI18N
        btnLast.setBoderColor(new java.awt.Color(145, 227, 168));
        btnLast.setRadius(10);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        panelRound2.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 60, 40));

        btnNext.setBackground(new java.awt.Color(145, 227, 168));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-right.png"))); // NOI18N
        btnNext.setBoderColor(new java.awt.Color(145, 227, 168));
        btnNext.setRadius(10);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panelRound2.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 60, 40));

        btnPrev.setBackground(new java.awt.Color(145, 227, 168));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-left.png"))); // NOI18N
        btnPrev.setBoderColor(new java.awt.Color(145, 227, 168));
        btnPrev.setRadius(10);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        panelRound2.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 40));

        btnFirst.setBackground(new java.awt.Color(145, 227, 168));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-left.png"))); // NOI18N
        btnFirst.setBoderColor(new java.awt.Color(145, 227, 168));
        btnFirst.setRadius(10);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        panelRound2.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 60, 40));

        cboTheLoai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboTheLoaiPropertyChange(evt);
            }
        });
        panelRound2.add(cboTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 270, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Theo thể loại");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 10, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Theo tác giả");
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 20));

        cboTacGia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboTacGiaPropertyChange(evt);
            }
        });
        panelRound2.add(cboTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 270, 40));

        tabTacGia.addTab("Phân loại", panelRound2);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFirst1.setBackground(new java.awt.Color(145, 227, 168));
        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-left.png"))); // NOI18N
        btnFirst1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnFirst1.setRadius(10);
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 60, 40));

        btnPrev1.setBackground(new java.awt.Color(145, 227, 168));
        btnPrev1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-left.png"))); // NOI18N
        btnPrev1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnPrev1.setRadius(10);
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 40));

        btnNext1.setBackground(new java.awt.Color(145, 227, 168));
        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-right.png"))); // NOI18N
        btnNext1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnNext1.setRadius(10);
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 60, 40));

        btnLast1.setBackground(new java.awt.Color(145, 227, 168));
        btnLast1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-right.png"))); // NOI18N
        btnLast1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnLast1.setRadius(10);
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 60, 40));

        panelRound4.setBackground(new java.awt.Color(232, 244, 234));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimTacGia.setBackground(new java.awt.Color(232, 244, 234));
        txtTimTacGia.setForeground(new java.awt.Color(51, 51, 51));
        txtTimTacGia.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        txtTimTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimTacGiaActionPerformed(evt);
            }
        });
        txtTimTacGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimTacGiaKeyPressed(evt);
            }
        });
        panelRound4.add(txtTimTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 40));

        btnTimTacGia.setBackground(new java.awt.Color(232, 244, 234));
        btnTimTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/search (1).png"))); // NOI18N
        btnTimTacGia.setBoderColor(new java.awt.Color(232, 244, 234));
        btnTimTacGia.setRadius(10);
        btnTimTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTacGiaActionPerformed(evt);
            }
        });
        panelRound4.add(btnTimTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 40));

        jPanel2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        tblTacGia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã mượn chi tiết", "Tên sách", "Tên đăng nhập", "Thời gian mượn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTacGia1.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTacGia1.getTableHeader().setReorderingAllowed(false);
        tblTacGia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacGia1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTacGia1);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 850, 290));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 530));

        jScrollPane3.setViewportView(jPanel1);

        panelRound3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 420));

        tabTacGia.addTab("Tài khoản mượn", panelRound3);

        panelRound5.setBackground(new java.awt.Color(254, 254, 254));
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDangNhapKeyPressed(evt);
            }
        });
        panelRound5.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 370, 40));

        lblTenDangNhap.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap.setText("Tài khoản mượn");
        panelRound5.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        txtMaSach.setBackground(new java.awt.Color(222, 247, 227));
        txtMaSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaSachKeyPressed(evt);
            }
        });
        panelRound5.add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 370, 40));

        lblMaSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaSach.setText("Mã sách mượn");
        panelRound5.add(lblMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtNgayMuon.setBackground(new java.awt.Color(222, 247, 227));
        panelRound5.add(txtNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 320, 40));

        lblNgayMuon.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblNgayMuon.setText("Ngày mượn");
        panelRound5.add(lblNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        Calendar.setBackground(new java.awt.Color(201, 235, 201));
        Calendar.setDecorationBackgroundColor(new java.awt.Color(153, 255, 153));
        Calendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        Calendar.setWeekdayForeground(new java.awt.Color(51, 51, 51));
        Calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarPropertyChange(evt);
            }
        });
        panelRound5.add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        btnIconCld1.setBackground(new java.awt.Color(87, 190, 110));
        btnIconCld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/calendar.png"))); // NOI18N
        btnIconCld1.setAutoscrolls(true);
        btnIconCld1.setBoderColor(new java.awt.Color(204, 204, 204));
        btnIconCld1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIconCld1MouseClicked(evt);
            }
        });
        panelRound5.add(btnIconCld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 50, 40));

        txtTenSach.setBackground(new java.awt.Color(222, 247, 227));
        txtTenSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenSachKeyPressed(evt);
            }
        });
        panelRound5.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 370, 40));

        lblTenSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach.setText("Tên sách mượn");
        panelRound5.add(lblTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        txtMaMuonSach.setBackground(new java.awt.Color(222, 247, 227));
        txtMaMuonSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaMuonSachKeyPressed(evt);
            }
        });
        panelRound5.add(txtMaMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 370, 40));

        lblMaMuonSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaMuonSach.setText("Mã mượn sách");
        panelRound5.add(lblMaMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        txtMaMuonSachChiTiet.setBackground(new java.awt.Color(222, 247, 227));
        txtMaMuonSachChiTiet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaMuonSachChiTietKeyPressed(evt);
            }
        });
        panelRound5.add(txtMaMuonSachChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, 40));

        lblMaMuonSachChiTiet.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaMuonSachChiTiet.setText("Mã mượn sách chi tiết");
        panelRound5.add(lblMaMuonSachChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(87, 190, 110));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBoderColor(new java.awt.Color(87, 190, 110));
        btnCapNhat.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnCapNhat.setRadius(10);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        panelRound5.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 120, 45));

        btnResetForm.setBackground(new java.awt.Color(87, 190, 110));
        btnResetForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/refresh (1).png"))); // NOI18N
        btnResetForm.setBoderColor(new java.awt.Color(87, 190, 110));
        btnResetForm.setRadius(10);
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });
        panelRound5.add(btnResetForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 45, 45));

        btnHuyMuon.setBackground(new java.awt.Color(255, 102, 102));
        btnHuyMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnHuyMuon.setBoderColor(new java.awt.Color(255, 102, 102));
        btnHuyMuon.setRadius(10);
        btnHuyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyMuonActionPerformed(evt);
            }
        });
        panelRound5.add(btnHuyMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 45, 45));

        tabTacGia.addTab("Thông tin chi tiết", panelRound5);

        pnlMain.add(tabTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 870, 460));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        pnlMain.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTheLoai_TacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTheLoai_TacGiaMouseClicked
        if (evt.getClickCount() == 2) {

        }
    }//GEN-LAST:event_tblTheLoai_TacGiaMouseClicked

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.last(index, tblTacGia, ListTG);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.next(index, tblTacGia, ListTG);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.previous(index, tblTacGia, ListTG);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.first(index, tblTacGia);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void tabTacGiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabTacGiaStateChanged

    }//GEN-LAST:event_tabTacGiaStateChanged

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void txtTimTacGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimTacGiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_txtTimTacGiaKeyPressed

    private void btnTimTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTacGiaActionPerformed

    }//GEN-LAST:event_btnTimTacGiaActionPerformed

    private void txtTimTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimTacGiaActionPerformed

    private void txtTenDangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhapKeyPressed

    }//GEN-LAST:event_txtTenDangNhapKeyPressed

    private void txtMaSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSachKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachKeyPressed

    private void CalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarPropertyChange
        txtNgayMuon.setText(String.valueOf(ShareHelper.formats.format(Calendar.getDate())));
    }//GEN-LAST:event_CalendarPropertyChange

    private void btnIconCld1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIconCld1MouseClicked
        Calendar.setVisible(congTac);
        congTac = !congTac;
    }//GEN-LAST:event_btnIconCld1MouseClicked

    private void txtTenSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSachKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachKeyPressed

    private void txtMaMuonSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaMuonSachKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMuonSachKeyPressed

    private void txtMaMuonSachChiTietKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaMuonSachChiTietKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMuonSachChiTietKeyPressed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetFormActionPerformed

    private void btnHuyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyMuonActionPerformed

    private void tblTacGia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacGia1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTacGia1MouseClicked

    private void cboTheLoaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboTheLoaiPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTheLoaiPropertyChange

    private void cboTacGiaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboTacGiaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTacGiaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManagerBorrowDiaLog dialog = new ManagerBorrowDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private com.ebooks.Compoment.MyButton btnCapNhat;
    private com.ebooks.Compoment.MyButton btnFirst;
    private com.ebooks.Compoment.MyButton btnFirst1;
    private com.ebooks.Compoment.MyButton btnHuyMuon;
    private com.ebooks.Compoment.MyButton btnIconCld1;
    private com.ebooks.Compoment.MyButton btnLast;
    private com.ebooks.Compoment.MyButton btnLast1;
    private com.ebooks.Compoment.MyButton btnNext;
    private com.ebooks.Compoment.MyButton btnNext1;
    private com.ebooks.Compoment.MyButton btnPrev;
    private com.ebooks.Compoment.MyButton btnPrev1;
    private com.ebooks.Compoment.MyButton btnResetForm;
    private com.ebooks.Compoment.MyButton btnTimTacGia;
    private javax.swing.JComboBox<String> cboTacGia;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblMaMuonSach;
    private javax.swing.JLabel lblMaMuonSachChiTiet;
    private javax.swing.JLabel lblMaSach;
    private javax.swing.JLabel lblNgayMuon;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblTenSach;
    private com.ebooks.Compoment.PanelRound panelRound2;
    private com.ebooks.Compoment.PanelRound panelRound3;
    private com.ebooks.Compoment.PanelRound panelRound4;
    private com.ebooks.Compoment.PanelRound panelRound5;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private com.ebooks.Compoment.PanelRound pnlMain;
    private javax.swing.JTabbedPane tabTacGia;
    private com.ebooks.Compoment.Table tblTacGia1;
    private com.ebooks.Compoment.Table tblTheLoai_TacGia;
    private javax.swing.JTextField txtMaMuonSach;
    private javax.swing.JTextField txtMaMuonSachChiTiet;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTenSach;
    private com.ebooks.Compoment.SearchText txtTimTacGia;
    // End of variables declaration//GEN-END:variables
}
